# Generated by Django 5.1.5 on 2025-01-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Teo va a picar código')),
                ('cod', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
            ],
        ),
    ]
